import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

import { Header } from "~/components/Header";
import { AuthBtn } from "~/components/AuthBtn";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Lyredium</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <IntroBloc />
      </main>
    </>
  );
}

function IntroBloc() {
  const { data: sessionData } = useSession();

  const formatName = (name: string | undefined | null) => {
    return name?.split(" ")[0];
  }

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Hey {formatName(sessionData.user?.name)}&#128075;</span>}
      </p>
      {!sessionData && <AuthBtn text={"Get started!"} 
        onClick={() => void signIn()}
        isTransparent={false}/>}
    </div>
  );
}
