import { signIn, useSession } from "next-auth/react";
import Head from "next/head";

import { api } from "~/utils/api";

import Header from "~/components/Header";
import Btn from "~/components/Btn";
import LoadingSpinner from "~/components/LoadingSpinner";
import PostView from "~/components/PostView";

export default function Home() {
  const { data: sessionData, status: userStatus } = useSession();
  const { data: posts, status: postsStatus } = api.post.getAll.useQuery();

  const isLoaded = userStatus !== "loading" && postsStatus !== "pending";
  const isAuth = sessionData;

  return (
    //extra div to override the literal one page where the bg-colour is different, u suck Medium.
    <div className={`${isAuth ? "bg-white" : "bg-orange-50"}`}>
      <Head>
        <title>Lyredium</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${!isAuth && "border-solid border-b-[1px] border-black py-4 px-8"}`}>
        <Header />
      </div>
      <main className="flex min-h-screen flex-col justify-start items-center py-8 gap-4">
        <div className="flex flex-col justify-start items-center w-full sm:w-1/2">
              {isLoaded ? isAuth ? posts?.map((post) => (
                <PostView post={post} key={post.id} />
              )) : 
              <IntroBloc />
              : <div className="flex items-center justify-center h-screen">
                  <LoadingSpinner />
                </div>}
        </div>
      </main>
    </div>
  );
}

function IntroBloc() {
  return (
    <div className="flex flex-col items-center justify-center gap-8 pt-20">
      <h1 className="font-serif font-medium text-8xl text-center">
        Human <br />
        stories & ideas
      </h1>
      <div className="flex flex-col items-center justify-center gap-6">
        <p className="text-lg">
          A place to read, write, and deepen your understanding.
        </p>
        <Btn text={"Start reading!"} 
          onClick={() => void signIn()}
          lightScheme={false}/>
      </div>
    </div>
  );
}
